// Banco de preguntas de opción múltiple sobre Valor Ganado (EVM).
// La sección Quiz elige 5 al azar en cada ronda para variar la experiencia.

export const QUESTION_BANK = [
  {
    id: "bac-def",
    question: "¿Qué representa el BAC (Presupuesto hasta la Conclusión)?",
    options: [
      "El dinero gastado hasta la fecha de corte",
      "El presupuesto total aprobado para todo el proyecto",
      "El valor del trabajo terminado a la fecha",
      "El costo estimado que falta para terminar",
    ],
    correct: 1,
    explanation: "El BAC es la línea base de costo: el presupuesto total aprobado para todo el alcance del proyecto, de principio a fin.",
  },
  {
    id: "vp-def",
    question: "¿Qué mide el Valor Planificado (VP)?",
    options: [
      "Cuánto trabajo debería estar hecho, en dinero, según el cronograma a la fecha",
      "Cuánto dinero se ha gastado realmente",
      "Cuánto vale el trabajo que ya se terminó",
      "El presupuesto total del proyecto",
    ],
    correct: 0,
    explanation: "El VP (Planned Value) es el valor, en términos de línea base, del trabajo que se planificó tener listo a una fecha determinada.",
  },
  {
    id: "vg-def",
    question: "¿Qué mide el Valor Ganado (VG)?",
    options: [
      "El dinero gastado hasta la fecha",
      "El valor, en dinero de línea base, del trabajo realmente completado",
      "El presupuesto total del proyecto",
      "El tiempo transcurrido del proyecto",
    ],
    correct: 1,
    explanation: "El VG traduce el trabajo físicamente terminado a la fecha en términos del presupuesto original, sin importar cuánto costó producirlo.",
  },
  {
    id: "cr-def",
    question: "¿Qué mide el Costo Real (CR)?",
    options: [
      "El dinero que efectivamente se ha gastado a la fecha para producir el trabajo",
      "El valor del trabajo planificado",
      "El presupuesto total aprobado",
      "El valor del trabajo terminado según la línea base",
    ],
    correct: 0,
    explanation: "El CR (Actual Cost) es el gasto real incurrido para ejecutar el trabajo realizado hasta la fecha de corte.",
  },
  {
    id: "vc-formula",
    question: "¿Cuál es la fórmula de la Variación del Costo (VC)?",
    options: ["VP − VG", "VG − CR", "CR − VG", "VG − VP"],
    correct: 1,
    explanation: "VC = VG − CR: compara el valor de lo entregado con lo que realmente costó producirlo.",
  },
  {
    id: "vs-formula",
    question: "¿Cuál es la fórmula de la Variación del Cronograma (VS)?",
    options: ["VG − VP", "VG − CR", "VP − VG", "CR − VP"],
    correct: 0,
    explanation: "VS = VG − VP: compara el trabajo realmente hecho con el trabajo que debía estar hecho según el plan.",
  },
  {
    id: "idc-formula",
    question: "¿Cuál es la fórmula del Índice de Desempeño del Costo (IDC)?",
    options: ["VP ÷ VG", "VG ÷ CR", "CR ÷ VG", "BAC ÷ VG"],
    correct: 1,
    explanation: "IDC = VG ÷ CR: cuánto valor se genera por cada unidad monetaria gastada.",
  },
  {
    id: "ids-formula",
    question: "¿Cuál es la fórmula del Índice de Desempeño del Cronograma (IDS)?",
    options: ["VG ÷ VP", "VP ÷ VG", "VG ÷ CR", "CR ÷ VP"],
    correct: 0,
    explanation: "IDS = VG ÷ VP: compara qué tan cerca está el avance real del avance planificado.",
  },
  {
    id: "idhc-formula",
    question: "¿Cuál es la fórmula del Índice de Desempeño Hasta la Conclusión (IDHC)?",
    options: [
      "(BAC − VG) ÷ (BAC − CR)",
      "(BAC − CR) ÷ (BAC − VG)",
      "VG ÷ (BAC − CR)",
      "(BAC − VG) ÷ CR",
    ],
    correct: 0,
    explanation: "IDHC = (BAC − VG) ÷ (BAC − CR): la eficiencia de costo que se necesita de ahora en adelante para cerrar el proyecto dentro del BAC.",
  },
  {
    id: "ecc-formula",
    question: "¿Cuál es la fórmula del Estimado de Costo para Concluir (ECC / EAC)?",
    options: ["BAC ÷ IDC", "BAC × IDC", "BAC − CR", "CR ÷ IDC"],
    correct: 0,
    explanation: "ECC = BAC ÷ IDC: proyecta el costo total del proyecto si el desempeño de costo actual se mantiene igual hasta el final.",
  },
  {
    id: "etc-formula",
    question: "¿Cuál es la fórmula del Estimado de Tiempo para Concluir (ETC de tiempo)?",
    options: [
      "(DTP − TT) ÷ IDS",
      "(DTP − TT) × IDS",
      "DTP ÷ IDS",
      "(BAC − VG) ÷ IDS",
    ],
    correct: 0,
    explanation: "ETC = (DTP − TT) ÷ IDS: el tiempo adicional proyectado para terminar, dado el ritmo actual de avance respecto al plan.",
  },
  {
    id: "vc-positive",
    question: "Si la Variación del Costo (VC) es mayor que 0, ¿qué significa?",
    options: [
      "El proyecto gastó más de lo que vale el trabajo entregado",
      "El trabajo entregado vale más de lo que costó producirlo (favorable)",
      "El proyecto va atrasado en el cronograma",
      "El presupuesto total se agotó",
    ],
    correct: 1,
    explanation: "VC > 0 es favorable: el valor de lo entregado supera el costo real incurrido, es decir, hay subejecución de costo.",
  },
  {
    id: "vc-negative",
    question: "Si la Variación del Costo (VC) es menor que 0, ¿qué significa?",
    options: [
      "El proyecto está adelantado en el cronograma",
      "El trabajo entregado vale más de lo que costó",
      "El proyecto gastó más de lo que vale el trabajo entregado (desfavorable)",
      "El IDC es mayor a 1",
    ],
    correct: 2,
    explanation: "VC < 0 es desfavorable: hubo sobrecosto, el costo real superó el valor del trabajo realmente entregado.",
  },
  {
    id: "vs-positive",
    question: "Si la Variación del Cronograma (VS) es mayor que 0, ¿qué indica?",
    options: [
      "El proyecto va adelantado respecto al cronograma planificado",
      "El proyecto va atrasado respecto al cronograma planificado",
      "El proyecto está gastando más de lo presupuestado",
      "El BAC se calculó mal",
    ],
    correct: 0,
    explanation: "VS > 0 significa que el valor ganado supera al valor planificado: el proyecto avanza más rápido de lo prometido.",
  },
  {
    id: "vs-negative",
    question: "Si la Variación del Cronograma (VS) es menor que 0, ¿qué indica?",
    options: [
      "El proyecto va adelantado",
      "El proyecto va atrasado respecto al cronograma planificado",
      "El costo real es igual al valor ganado",
      "El IDS es mayor a 1",
    ],
    correct: 1,
    explanation: "VS < 0 significa que el valor ganado es menor al planificado: el proyecto va atrasado respecto al cronograma.",
  },
  {
    id: "idc-greater-1",
    question: "Si el IDC es mayor que 1, ¿qué significa?",
    options: [
      "Por cada unidad monetaria gastada se genera menos de una unidad de valor",
      "El proyecto va atrasado en el cronograma",
      "Por cada unidad monetaria gastada se genera más de una unidad de valor (eficiente)",
      "El presupuesto ya se agotó",
    ],
    correct: 2,
    explanation: "IDC > 1 indica eficiencia en el uso del presupuesto: se produce más valor del que cuesta cada unidad gastada.",
  },
  {
    id: "idc-less-1",
    question: "Si el IDC es menor que 1, ¿qué significa?",
    options: [
      "El proyecto es eficiente en costos",
      "Por cada unidad monetaria gastada se genera menos de una unidad de valor (ineficiente)",
      "El proyecto va adelantado en el cronograma",
      "El VC es positivo",
    ],
    correct: 1,
    explanation: "IDC < 1 indica ineficiencia: se está gastando más dinero del que se recupera en valor de trabajo entregado.",
  },
  {
    id: "ids-greater-1",
    question: "Si el IDS es mayor que 1, ¿qué significa?",
    options: [
      "El proyecto va atrasado respecto al plan",
      "El ritmo de avance real supera al ritmo planificado (adelantado)",
      "El proyecto gasta más de lo presupuestado",
      "El BAC aumentó",
    ],
    correct: 1,
    explanation: "IDS > 1 significa que el proyecto avanza más rápido de lo planificado.",
  },
  {
    id: "ids-less-1",
    question: "Si el IDS es menor que 1, ¿qué significa?",
    options: [
      "El ritmo de avance real es más lento que el planificado (atrasado)",
      "El proyecto va adelantado",
      "El IDC también es menor a 1 necesariamente",
      "El CR es igual al VP",
    ],
    correct: 0,
    explanation: "IDS < 1 significa que el proyecto avanza más lento de lo planificado: hay atraso en el cronograma.",
  },
  {
    id: "vc-numeric",
    question: "Si VG = $80.000.000 y CR = $95.000.000, ¿cuál es la Variación del Costo (VC)?",
    options: ["$15.000.000 (favorable)", "-$15.000.000 (desfavorable)", "$175.000.000", "$0"],
    correct: 1,
    explanation: "VC = VG − CR = 80.000.000 − 95.000.000 = −$15.000.000: el proyecto gastó 15 millones más de lo que vale el trabajo entregado.",
  },
  {
    id: "vs-numeric",
    question: "Si VG = $60.000.000 y VP = $50.000.000, ¿cuál es la Variación del Cronograma (VS)?",
    options: ["-$10.000.000", "$10.000.000 (adelantado)", "$110.000.000", "No se puede calcular"],
    correct: 1,
    explanation: "VS = VG − VP = 60.000.000 − 50.000.000 = $10.000.000: el proyecto va adelantado respecto al plan.",
  },
  {
    id: "idc-numeric",
    question: "Si VG = $90.000.000 y CR = $100.000.000, ¿cuál es el IDC (aproximado)?",
    options: ["1.11", "0.90", "10.00", "1.00"],
    correct: 1,
    explanation: "IDC = VG ÷ CR = 90 ÷ 100 = 0.90: por cada peso gastado se generan solo 0.90 de valor, es decir, ineficiencia de costo.",
  },
  {
    id: "ids-numeric",
    question: "Si VG = $45.000.000 y VP = $50.000.000, ¿cuál es el IDS (aproximado)?",
    options: ["1.11", "0.90", "5.00", "0.50"],
    correct: 1,
    explanation: "IDS = VG ÷ VP = 45 ÷ 50 = 0.90: el proyecto avanza al 90% de la velocidad planificada, va atrasado.",
  },
  {
    id: "evm-purpose",
    question: "¿Cuál es el propósito principal de la técnica de Valor Ganado (EVM)?",
    options: [
      "Calcular únicamente cuánto dinero se ha gastado en el proyecto",
      "Integrar alcance, cronograma y costo para medir objetivamente el desempeño del proyecto",
      "Reemplazar el cronograma del proyecto",
      "Definir el alcance inicial del proyecto",
    ],
    correct: 1,
    explanation: "EVM integra tres dimensiones (alcance, tiempo y costo) en un solo análisis objetivo de desempeño, en lugar de mirarlas por separado.",
  },
  {
    id: "cr-vs-vp",
    question: "¿Cuál es la diferencia clave entre el Costo Real (CR) y el Valor Planificado (VP)?",
    options: [
      "Son exactamente lo mismo",
      "CR es lo que realmente se gastó; VP es lo que se planeó tener hecho, en dinero, a la fecha",
      "VP es lo que realmente se gastó; CR es el presupuesto total",
      "CR solo aplica al final del proyecto",
    ],
    correct: 1,
    explanation: "El CR refleja gasto real ejecutado; el VP refleja lo que el cronograma decía que debía estar listo, ambos evaluados a la misma fecha de corte.",
  },
  {
    id: "idc-undefined",
    question: "Si el Costo Real (CR) es igual a 0, ¿qué ocurre con el IDC?",
    options: [
      "El IDC es siempre 1",
      "El IDC no se puede calcular (división entre cero)",
      "El IDC es siempre 0",
      "El IDC se calcula usando el BAC en su lugar",
    ],
    correct: 1,
    explanation: "Dividir VG entre un CR de 0 no tiene un resultado numérico válido, por lo que el indicador queda indefinido hasta que haya gasto real registrado.",
  },
  {
    id: "ids-undefined",
    question: "Si el Valor Planificado (VP) es igual a 0, ¿qué ocurre con el IDS?",
    options: [
      "El IDS no se puede calcular (división entre cero)",
      "El IDS es siempre 1",
      "El IDS es igual al IDC",
      "El IDS es siempre mayor a 1",
    ],
    correct: 0,
    explanation: "Si no se había planificado ningún valor a esa fecha (VP = 0), la división VG ÷ VP queda indefinida.",
  },
  {
    id: "idhc-greater-1",
    question: "Si el IDHC calculado es mayor a 1, ¿qué le dice esto al equipo del proyecto?",
    options: [
      "Que puede relajar el ritmo de trabajo",
      "Que debe rendir mejor de lo que ha rendido hasta ahora para no exceder el BAC",
      "Que el proyecto ya terminó",
      "Que el presupuesto sobrará",
    ],
    correct: 1,
    explanation: "IDHC > 1 significa que la eficiencia futura requerida es mayor a la lograda hasta hoy: hay que mejorar el desempeño de costo para cerrar dentro del presupuesto aprobado.",
  },
  {
    id: "tt-dtp-def",
    question: "¿Qué representan el Tiempo Transcurrido (TT) y la Duración Total Planificada (DTP)?",
    options: [
      "TT es el dinero gastado y DTP el presupuesto total",
      "TT son los meses ya pasados desde el inicio; DTP es la duración total estimada del proyecto",
      "Son sinónimos del VP y el VG",
      "TT es el avance físico y DTP el costo real",
    ],
    correct: 1,
    explanation: "TT mide cuánto tiempo de calendario ya transcurrió; DTP es la duración total que se estimó para todo el proyecto, ambos usados para proyectar el ETC.",
  },
  {
    id: "three-base-variables",
    question: "¿Cuáles son las tres variables medidas en campo sobre las que se construye todo el análisis de Valor Ganado?",
    options: [
      "BAC, DTP y TT",
      "VP, VG y CR",
      "VC, VS e IDC",
      "IDC, IDS e IDHC",
    ],
    correct: 1,
    explanation: "VP (lo planificado), VG (lo realmente hecho) y CR (lo realmente gastado) son las tres mediciones base; el resto de indicadores se derivan combinándolas con el BAC.",
  },
];
